name: Build with nix
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run `nix build`
        run: nix build .
      - name: Upload nix result
        uses: actions/upload-artifact@v4.4.3
        with:
          name: rwds-cli-bin-linux-x86_64
          path: result
  
  
